spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_profile_spring
    username: postgres
    password: saif
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect